//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTileCustomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTileCustomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerard Balaoro.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsTileCustomizer is a tool for customizing start menu tiles for Windows Desktop Applications..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/GerardBalaoro/MetroTileCustomizer/blob/master/LICENSE.
        /// </summary>
        internal static string AboutLicenseUrl {
            get {
                return ResourceManager.GetString("AboutLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/GerardBalaoro/WindowsTileCustomizer.
        /// </summary>
        internal static string AboutWebsite {
            get {
                return ResourceManager.GetString("AboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f7fafc
        ///#edf2f7
        ///#e2e8f0
        ///#cbd5e0
        ///#a0aec0
        ///#718096
        ///#4a5568
        ///#2d3748
        ///#1a202c
        ///#fff5f5
        ///#fed7d7
        ///#feb2b2
        ///#fc8181
        ///#f56565
        ///#e53e3e
        ///#c53030
        ///#9b2c2c
        ///#742a2a
        ///#fffaf0
        ///#feebc8
        ///#fbd38d
        ///#f6ad55
        ///#ed8936
        ///#dd6b20
        ///#c05621
        ///#9c4221
        ///#7b341e
        ///#fffff0
        ///#fefcbf
        ///#faf089
        ///#f6e05e
        ///#ecc94b
        ///#d69e2e
        ///#b7791f
        ///#975a16
        ///#744210
        ///#f0fff4
        ///#c6f6d5
        ///#9ae6b4
        ///#68d391
        ///#48bb78
        ///#38a169
        ///#2f855a
        ///#276749
        ///#22543d
        ///#e6fffa
        ///#b2f5ea
        ///#81e6d9
        ///#4fd1c5
        ///#38b2ac
        ///#319795
        ///#2c7a7b
        ///#285e61
        ///#234e52
        ///#ebf8ff
        ///#bee3f8
        ///#90cdf4        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_eyedrop {
            get {
                object obj = ResourceManager.GetObject("ionicons_eyedrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_palette {
            get {
                object obj = ResourceManager.GetObject("ionicons_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octicons_globe {
            get {
                object obj = ResourceManager.GetObject("octicons_globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octicons_law {
            get {
                object obj = ResourceManager.GetObject("octicons_law", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octicons_tag {
            get {
                object obj = ResourceManager.GetObject("octicons_tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
